## Laravel Filament Flexible Content Block Pages

This package is a CMS for Filament, built on `statikbe/laravel-filament-flexible-content-blocks`.
It provides pages with flexible content blocks, a menu builder, CMS settings, tags with SEO tag
pages, redirects and a sitemap. Its models are `Page`, `Settings`, `Menu`, `MenuItem`, `Tag`,
`TagType` and `Redirect`, all in `Statikbe\FilamentFlexibleContentBlockPages\Models`.

### Never edit the package, extend and register

Every model and Filament resource of the package can be replaced by your own subclass. Extend the
package class, then register it in `config/filament-flexible-content-block-pages.php` under
`models.*` and `resources.*`. Code that is not registered in the config is never used.

@verbatim
<code-snippet name="Extend a package model and register it" lang="php">
// app/Models/CmsPage.php
class CmsPage extends \Statikbe\FilamentFlexibleContentBlockPages\Models\Page {}

// config/filament-flexible-content-block-pages.php
'models' => [
    'pages' => \App\Models\CmsPage::class,
],
</code-snippet>
@endverbatim

### Never hardcode a package model or resource

Resolve the configured model or resource through the config object, so projects that extend a model
keep working:

@verbatim
<code-snippet name="Resolve the configured model, resource and table" lang="php">
use Statikbe\FilamentFlexibleContentBlockPages\Facades\FilamentFlexibleContentBlockPages;

$pageModel = FilamentFlexibleContentBlockPages::config()->getPageModel();       // model instance
$settings = FilamentFlexibleContentBlockPages::config()->getSettingsModel();    // model instance
$resource = FilamentFlexibleContentBlockPages::config()->getPageResource();     // resource class
$table = FilamentFlexibleContentBlockPages::config()->getSettingsTable();       // table name
</code-snippet>
@endverbatim

### Helpers

@verbatim
<code-snippet name="Package helper functions" lang="php">
// CMS settings, cached per locale:
$title = flexiblePagesSetting(Settings::SETTING_SITE_TITLE, default: config('app.name'));
$logo = flexiblePagesSettingImageUrl(Settings::COLLECTION_DEFAULT_SEO, Settings::CONVERSION_DEFAULT_SEO);

// translations of the package and its morph aliases:
$label = flexiblePagesTrans('settings.settings_site_title');
$morphAlias = flexiblePagesPrefix('page'); // filament-flexible-content-block-pages::page
</code-snippet>
@endverbatim

### Conventions

- Settings live in one record, one column per setting. Media settings are media library
  collections, not columns. Add a setting with the `add-flexible-pages-setting` skill.
- Translatable fields use Spatie translatable with `json` columns, and Filament fields get the
  translation hint `flexiblePagesTrans('settings.translatable_field_hint')`.
- Models that must be linkable in menus and the sitemap implement `HasMenuLabel`.
- Pages are hierarchical, up to 3 levels. URLs are generated by the configured `route_helper`,
  never by concatenating slugs yourself.
- Frontend views are customised by publishing them with
  `php artisan vendor:publish --tag="filament-flexible-content-block-pages-views"`, not by editing
  the package.
- In Filament code always use existing Filament components (`<x-filament::button>`,
  `<x-filament::badge>`, form components, actions, notifications) instead of custom HTML or CSS.
- Package translations live in `resources/lang/vendor/filament-flexible-content-block-pages`, your
  own labels in your app's translation files. Never hardcode UI labels.
